import{S as A,a as m,i as f}from"./assets/vendor-CZ-iLBCt.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const n=document.querySelector(".gallery"),l=document.querySelector(".loader");function p(r){const a=r.map(({webformatURL:o,tags:e,largeImageURL:t,likes:s,views:c,comments:d,downloads:u})=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${t}">
                <img src="${o}" alt="${e}">
                <div class="image-stats">
                    <p class="img-stat-text"><span class="img-stat-header">Likes</span> ${s}</p>
                    <p class="img-stat-text"><span class="img-stat-header">Views</span> ${c}</p>
                    <p class="img-stat-text"><span class="img-stat-header">Comments</span> ${d}</p>
                    <p class="img-stat-text"><span class="img-stat-header">Downloads</span> ${u}</p>
                </div>
            </a>
        </li>
    `).join("");n.insertAdjacentHTML("beforeend",a),new A(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh()}function g(){n.innerHTML=""}function h(){l.classList.toggle("hidden")}function y(){l.classList.toggle("hidden")}const L="51390103-e5f94b12a87f57c9fbe51ad97";function E(r){return h(),m("https://pixabay.com/api/",{params:{key:L,q:`${r}`,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(a=>(p(a.data.hits),a.data.hits)).catch(a=>{console.log(a)}).finally(()=>{y()})}const b="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAJcEhZcwAACxMAAAsTAQCanBgAAAAhUExURfn5+/v7+/n5+0dwTPr6/Pn5+vn5+/r6+vT0+vT09Pr6+69tr8QAAAAKdFJOU4B/fwCfoK8wMDCbJE/NAAAAn0lEQVQY00XQIY7DMBCG0ZHMzEJLzYyiPEW7vLfoEULLSvcirrWKVJ9ywTYNfPrI/BPIY4zREMz7NE3TlgjyFdZGmH+BWxLvwNrEEbilyFdfcLe22Hkk5hdbPFkauXCJJ2qauwNLy+UDtTuR24m51/RBLks7MHdq4hI7j8LyYot69Q0/1h7LeWgJ9ZjQhSPdivBOaydY/h9SCNQxxuj4A4bdSawyd2feAAAAAElFTkSuQmCC",S=document.querySelector(".form"),x=document.querySelector('input[name="search-text"]');S.addEventListener("submit",r=>{r.preventDefault(),g(),E(x.value.trim()).then(a=>{a.length||f.error({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fafafb",messageSize:16,messageLineHeight:24,position:"topRight",displayMode:"replace",closeOnEscape:!0,closeOnClick:!0,iconUrl:b,theme:"dark",backgroundColor:"#ef4040",maxWidth:432})})});
//# sourceMappingURL=index.js.map
