import{S as p,a as A,i as l}from"./assets/vendor-CZ-iLBCt.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&i(r)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const d=document.querySelector(".gallery"),u=document.querySelector(".loader");function g(a){const s=a.map(({webformatURL:o,tags:i,largeImageURL:e,likes:t,views:r,comments:m,downloads:f})=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${e}">
                <img src="${o}" alt="${i}">
                <div class="image-stats">
                    <p class="img-stat-text"><span class="img-stat-header">Likes</span> ${t}</p>
                    <p class="img-stat-text"><span class="img-stat-header">Views</span> ${r}</p>
                    <p class="img-stat-text"><span class="img-stat-header">Comments</span> ${m}</p>
                    <p class="img-stat-text"><span class="img-stat-header">Downloads</span> ${f}</p>
                </div>
            </a>
        </li>
    `).join("");d.insertAdjacentHTML("beforeend",s),h.refresh()}let h=new p(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});function y(){d.innerHTML=""}function L(){u.classList.remove("hidden")}function E(){u.classList.add("hidden")}const S="51390103-e5f94b12a87f57c9fbe51ad97";function b(a){return L(),A("https://pixabay.com/api/",{params:{key:S,q:`${a}`,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(s=>s.data.hits).catch(s=>{n(s.message)}).finally(()=>{E()})}const v="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAJcEhZcwAACxMAAAsTAQCanBgAAAAhUExURfn5+/v7+/n5+0dwTPr6/Pn5+vn5+/r6+vT0+vT09Pr6+69tr8QAAAAKdFJOU4B/fwCfoK8wMDCbJE/NAAAAn0lEQVQY00XQIY7DMBCG0ZHMzEJLzYyiPEW7vLfoEULLSvcirrWKVJ9ywTYNfPrI/BPIY4zREMz7NE3TlgjyFdZGmH+BWxLvwNrEEbilyFdfcLe22Hkk5hdbPFkauXCJJ2qauwNLy+UDtTuR24m51/RBLks7MHdq4hI7j8LyYot69Q0/1h7LeWgJ9ZjQhSPdivBOaydY/h9SCNQxxuj4A4bdSawyd2feAAAAAElFTkSuQmCC",w=document.querySelector(".form"),c=document.querySelector('input[name="search-text"]');w.addEventListener("submit",a=>{if(a.preventDefault(),y(),!c.value){n("Empty input. Please type images you want ot find!");return}b(c.value.trim()).then(s=>{if(!s.length){n("Sorry, there are no images matching your search query. Please try again!");return}g(s),l.success({message:"This is what was found!",position:"topLeft",messageSize:16,messageLineHeight:24,closeOnEscape:!0,closeOnClick:!0})})});function n(a){l.error({message:a,messageColor:"#fafafb",messageSize:16,messageLineHeight:24,position:"topRight",displayMode:"replace",closeOnEscape:!0,closeOnClick:!0,iconUrl:v,theme:"dark",backgroundColor:"#ef4040",maxWidth:432})}
//# sourceMappingURL=index.js.map
